/*{"created":"2011-03-21T23:07:41Z","mac":"1:c4ab87a8979f52fef0242ec0251791ba54c074841541956f833e8cc632dfda17","version":"3336789","k":"0.8.0"}*/
;(function(window,document,undefined){
var i=true,l=null,q=false;function r(a){return function(){return this[a]}}var s;function t(a,c){var b=arguments.length>2?Array.prototype.slice.call(arguments,2):[];return function(){b.push.apply(b,arguments);return c.apply(a,b)}}function u(a,c){this.o=a;this.f=c}s=u.prototype;
s.createElement=function(a,c,b){a=this.o.createElement(a);if(c)for(var d in c)if(c.hasOwnProperty(d))if(d=="style"&&this.f.getName()=="MSIE")a.style.cssText=c[d];else a.setAttribute(d,c[d]);b&&a.appendChild(this.o.createTextNode(b));return a};s.insertInto=function(a,c){var b=this.o.getElementsByTagName(a)[0];if(!b)b=document.documentElement;if(b&&b.lastChild){b.insertBefore(c,b.lastChild);return i}return q};s.whenBodyExists=function(a){function c(){document.body?a():setTimeout(c,0)}c()};
s.removeElement=function(a){if(a.parentNode){a.parentNode.removeChild(a);return i}return q};s.createCssLink=function(a){return this.createElement("link",{rel:"stylesheet",href:a})};s.appendClassName=function(a,c){for(var b=a.className.split(/\s+/),d=0,e=b.length;d<e;d++)if(b[d]==c)return;b.push(c);a.className=b.join(" ").replace(/^\s+/,"")};
s.removeClassName=function(a,c){for(var b=a.className.split(/\s+/),d=[],e=0,f=b.length;e<f;e++)b[e]!=c&&d.push(b[e]);a.className=d.join(" ").replace(/^\s+/,"").replace(/\s+$/,"")};s.hasClassName=function(a,c){for(var b=a.className.split(/\s+/),d=0,e=b.length;d<e;d++)if(b[d]==c)return i;return q};function v(a,c,b,d,e,f,k,g){this.ra=a;this.Da=c;this.ha=b;this.ga=d;this.wa=e;this.va=f;this.fa=k;this.Ea=g}s=v.prototype;s.getName=r("ra");s.getVersion=r("Da");s.getEngine=r("ha");s.getEngineVersion=r("ga");
s.getPlatform=r("wa");s.getPlatformVersion=r("va");s.getDocumentMode=r("fa");function w(a,c){this.f=a;this.r=c}var aa=new v("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",undefined,q);
w.prototype.parse=function(){var a;if(this.f.indexOf("MSIE")!=-1){a=x(this,this.f,/(MSIE [\d\w\.]+)/,1);if(a!=""){var c=a.split(" ");a=c[0];c=c[1];a=new v(a,c,a,c,y(this),z(this),A(this,this.r),B(this,c)>=6)}else a=new v("MSIE","Unknown","MSIE","Unknown",y(this),z(this),A(this,this.r),q)}else{if(this.f.indexOf("Opera")!=-1)a:{c=a="Unknown";var b=x(this,this.f,/(Presto\/[\d\w\.]+)/,1);if(b!=""){c=b.split("/");a=c[0];c=c[1]}else{if(this.f.indexOf("Gecko")!=-1)a="Gecko";b=x(this,this.f,/rv:([^\)]+)/,
1);if(b!="")c=b}if(this.f.indexOf("Version/")!=-1){b=x(this,this.f,/Version\/([\d\.]+)/,1);if(b!=""){a=new v("Opera",b,a,c,y(this),z(this),A(this,this.r),B(this,b)>=10);break a}}b=x(this,this.f,/Opera[\/ ]([\d\.]+)/,1);a=b!=""?new v("Opera",b,a,c,y(this),z(this),A(this,this.r),B(this,b)>=10):new v("Opera","Unknown",a,c,y(this),z(this),A(this,this.r),q)}else{if(this.f.indexOf("AppleWebKit")!=-1){a=y(this);c=z(this);b=x(this,this.f,/AppleWebKit\/([\d\.]+)/,1);if(b=="")b="Unknown";var d="Unknown";
if(this.f.indexOf("Chrome")!=-1)d="Chrome";else if(this.f.indexOf("Safari")!=-1)d="Safari";else if(this.f.indexOf("AdobeAIR")!=-1)d="AdobeAIR";var e="Unknown";if(this.f.indexOf("Version/")!=-1)e=x(this,this.f,/Version\/([\d\.\w]+)/,1);else if(d=="Chrome")e=x(this,this.f,/Chrome\/([\d\.]+)/,1);else if(d=="AdobeAIR")e=x(this,this.f,/AdobeAIR\/([\d\.]+)/,1);var f=q;if(d=="AdobeAIR"){f=x(this,e,/\d+\.(\d+)/,1);f=B(this,e)>2||B(this,e)==2&&parseInt(f,10)>=5}else{f=x(this,b,/\d+\.(\d+)/,1);f=B(this,b)>=
526||B(this,b)>=525&&parseInt(f,10)>=13}a=new v(d,e,"AppleWebKit",b,a,c,A(this,this.r),f)}else{if(this.f.indexOf("Gecko")!=-1){c=a="Unknown";d=q;if(this.f.indexOf("Firefox")!=-1){a="Firefox";b=x(this,this.f,/Firefox\/([\d\w\.]+)/,1);if(b!=""){d=x(this,b,/\d+\.(\d+)/,1);c=b;d=b!=""&&B(this,b)>=3&&parseInt(d,10)>=5}}else if(this.f.indexOf("Mozilla")!=-1)a="Mozilla";b=x(this,this.f,/rv:([^\)]+)/,1);if(b=="")b="Unknown";else if(!d){d=B(this,b);e=parseInt(x(this,b,/\d+\.(\d+)/,1),10);f=parseInt(x(this,
b,/\d+\.\d+\.(\d+)/,1),10);d=d>1||d==1&&e>9||d==1&&e==9&&f>=2||b.match(/1\.9\.1b[123]/)!=l||b.match(/1\.9\.1\.[\d\.]+/)!=l}a=new v(a,c,"Gecko",b,y(this),z(this),A(this,this.r),d)}else a=aa;a=a}a=a}a=a}return a};function y(a){var c=x(a,a.f,/(iPod|iPad|iPhone|Android)/,1);if(c!="")return c;a=x(a,a.f,/(Linux|Mac_PowerPC|Macintosh|Windows)/,1);if(a!=""){if(a=="Mac_PowerPC")a="Macintosh";return a}return"Unknown"}
function z(a){var c=x(a,a.f,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(c)return c;if(c=x(a,a.f,/(iPhone )?OS ([\d_]+)/,2))return c;if(a=x(a,a.f,/Linux ([i\d]+)/,1))return a;return"Unknown"}function B(a,c){var b=x(a,c,/(\d+)/,1);if(b!="")return parseInt(b,10);return-1}function x(a,c,b,d){if((a=c.match(b))&&a[d])return a[d];return""}function A(a,c){if(c.documentMode)return c.documentMode}function ba(a,c,b,d){this.i=a;this.k=c;this.L=b;this.m=d||"wf";this.l=new C("-")}
function D(a){a.i.removeClassName(a.k,a.l.j(a.m,"loading"));a.i.hasClassName(a.k,a.l.j(a.m,"active"))||a.i.appendClassName(a.k,a.l.j(a.m,"inactive"));E(a,"inactive")}function E(a,c,b,d){a.L[c]&&a.L[c](b,d)}function G(a,c,b,d,e){this.i=a;this.u=c;this.v=b;this.p=d;this.G=e;this.N=0;this.aa=this.U=q}
G.prototype.watch=function(a,c,b,d){for(var e=a.length,f=0;f<e;f++){var k=a[f];c[k]||(c[k]=["n4"]);this.N+=c[k].length}if(d)this.U=d;for(f=0;f<e;f++){k=a[f];d=c[k];for(var g=b[k],h=0,m=d.length;h<m;h++){var o=d[h],p=this.u,j=k,n=o;p.i.appendClassName(p.k,p.l.j(p.m,j,n,"loading"));E(p,"fontloading",j,n);p=t(this,this.ia);j=t(this,this.ja);new H(p,j,this.i,this.v,this.p,this.G,k,o,g)}}};
G.prototype.ia=function(a,c){var b=this.u;b.i.removeClassName(b.k,b.l.j(b.m,a,c,"loading"));b.i.removeClassName(b.k,b.l.j(b.m,a,c,"inactive"));b.i.appendClassName(b.k,b.l.j(b.m,a,c,"active"));E(b,"fontactive",a,c);this.aa=i;I(this)};G.prototype.ja=function(a,c){var b=this.u;b.i.removeClassName(b.k,b.l.j(b.m,a,c,"loading"));b.i.hasClassName(b.k,b.l.j(b.m,a,c,"active"))||b.i.appendClassName(b.k,b.l.j(b.m,a,c,"inactive"));E(b,"fontinactive",a,c);I(this)};
function I(a){if(--a.N==0&&a.U)if(a.aa){a=a.u;a.i.removeClassName(a.k,a.l.j(a.m,"loading"));a.i.removeClassName(a.k,a.l.j(a.m,"inactive"));a.i.appendClassName(a.k,a.l.j(a.m,"active"));E(a,"active")}else D(a.u)}
function H(a,c,b,d,e,f,k,g,h){this.ca=a;this.ma=c;this.i=b;this.v=d;this.p=e;this.G=f;this.qa=new J;this.la=new K;this.Q=k;this.P=g;this.ka=h||"BESs";this.ta=L(this,"arial,'URW Gothic L',sans-serif");this.ua=L(this,"Georgia,'Century Schoolbook L',serif");this.Y=M(this,"arial,'URW Gothic L',sans-serif");this.Z=M(this,"Georgia,'Century Schoolbook L',serif");this.Ca=f();this.M()}
H.prototype.M=function(){var a=this.v.H(this.Z);if(this.ta!=this.v.H(this.Y)||this.ua!=a)N(this,this.ca);else this.G()-this.Ca<5E3?ca(this):N(this,this.ma)};function ca(a){a.p(function(c,b){return function(){b.call(c)}}(a,a.M),50)}function N(a,c){a.i.removeElement(a.Y);a.i.removeElement(a.Z);c(a.Q,a.P)}function L(a,c){var b=M(a,c,i),d=a.v.H(b);a.i.removeElement(b);return d}
function M(a,c,b){var d=a.la.expand(a.P);c=a.i.createElement("span",{style:"position:absolute;top:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;font-family:"+(b?"":a.qa.quote(a.Q)+",")+c+";"+d},a.ka);a.i.insertInto("body",c);return c}function C(a){this.oa=a||"-"}C.prototype.j=function(){for(var a=[],c=0;c<arguments.length;c++)a.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return a.join(this.oa)};function J(){this.X="'"}
J.prototype.quote=function(a){var c=[];a=a.split(/,\s*/);for(var b=0;b<a.length;b++){var d=a[b].replace(/['"]/g,"");d.indexOf(" ")==-1?c.push(d):c.push(this.X+d+this.X)}return c.join(",")};function K(){this.W=da;this.z=ea}var da=["font-style","font-weight"],ea={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};
function O(a,c,b){this.na=a;this.xa=c;this.z=b}O.prototype.expand=function(a,c){for(var b=0;b<this.z.length;b++)if(c==this.z[b][0]){a[this.na]=this.xa+":"+this.z[b][1];break}};K.prototype.expand=function(a){if(a.length!=2)return l;for(var c=[l,l],b=0,d=this.W.length;b<d;b++){var e=this.W[b];(new O(b,e,this.z[e])).expand(c,a.substr(b,1))}return c[0]&&c[1]?c.join(";")+";":l};function P(a,c){this.o=a;this.f=c}P.prototype=u.prototype;P.prototype.isHttps=function(){return this.o.location.protocol=="https:"};
P.prototype.loadScript=function(a,c){var b=this.o.getElementsByTagName("head")[0];if(b){var d=this.o.createElement("script");d.src=a;var e=q;d.onload=d.onreadystatechange=function(){if(!e&&(!this.readyState||this.readyState=="loaded"||this.readyState=="complete")){e=i;c&&c();d.onload=d.onreadystatechange=l;d.parentNode.tagName=="HEAD"&&b.removeChild(d)}};b.appendChild(d)}};
P.prototype.createStyle=function(a){var c=this.o.createElement("style");c.setAttribute("type","text/css");if(c.styleSheet)c.styleSheet.cssText=a;else c.appendChild(document.createTextNode(a));return c};function fa(a){for(var c=a.Aa.join(","),b=[],d=0;d<a.O.length;d++){var e=a.O[d];b.push(e.name+":"+e.value+";")}return c+"{"+b.join("")+"}"}function Q(a,c){this.A=a;this.R=c}
Q.prototype.watch=function(a,c,b){var d=[],e={};d.push(this.A);e[this.A]=this.R[c.getStylesheetFormatId()]||[];a.watch(d,e,{},b)};function R(a,c,b){this.Ba=a;this.I=c;this.ya=b}R.prototype.buildUrl=function(a,c){var b=this.Ba&&a?"https:":"http:",d=typeof this.I=="function"?this.I(b):this.I;return b+"//"+d+this.ya+c};
function ga(a,c,b){if(a.S){var d=function(){try{c._gat._getTracker("UA-8850781-3")._trackPageview();c.tkKitsTracked||(c.tkKitsTracked=0);c.tkKitsTracked++}catch(e){}};if(c._gat)d();else{a=a.S.buildUrl(b.isHttps(),"/ga.js");b.loadScript(a,d)}}}function S(a,c,b){this.w=a;this.$=c;this.T=b}S.prototype.getId=r("w");S.prototype.getStylesheetFormatId=r("$");
S.prototype.isUserAgent=function(a){return this.T?this.T(a.getName(),a.getVersion(),a.getEngine(),a.getEngineVersion(),a.getPlatform(),a.getPlatformVersion(),a.getDocumentMode()):q};S.prototype.buildCssUrl=function(a,c,b,d){b="/"+b+"-"+this.$+".css";if(d)b+="?"+d;return c.buildUrl(a,b)};function T(){this.q=[]}T.prototype.addBrowser=function(a){this.getBrowserById(a.getId())||this.q.push(a)};T.prototype.getBrowserById=function(a){for(var c=0;c<this.q.length;c++){var b=this.q[c];if(a===b.getId())return b}return l};
T.prototype.findBrowser=function(a){for(var c=0;c<this.q.length;c++){var b=this.q[c];if(b.isUserAgent(a))return b}return l};T.prototype.addBrowsersToBrowserSet=function(a){for(var c=0;c<this.q.length;c++)a.addBrowser(this.q[c])};function ha(a){this.w=a;this.D=new T;this.s=[];this.F=[]}s=ha.prototype;s.getId=r("w");s.setSecurityToken=function(a){this.za=a};s.setNestedUrl=function(a){this.sa=a};s.setKitOptions=function(a){this.B=a};s.addBrowser=function(a){this.D.addBrowser(a)};s.addFontFamily=function(a){this.s.push(a)};
s.addCssRule=function(a){this.F.push(a)};s.supportsBrowser=function(a){return!!this.D.getBrowserById(a.getId())};s.addBrowsersToBrowserSet=function(a){this.D.addBrowsersToBrowserSet(a)};s.init=function(a){for(var c=[],b=0;b<this.F.length;b++)c.push(fa(this.F[b]));a.insertInto("head",a.createStyle(c.join("")))};
s.load=function(a,c,b,d){var e=b.buildCssUrl(a.isHttps(),this.sa,this.w,this.za);a.insertInto("head",a.createCssLink(e));c&&a.whenBodyExists(function(f,k,g,h){return function(){for(var m=0;m<f.s.length;m++)f.s[m].watch(k,g,h&&m==f.s.length-1)}}(this,c,b,d))};s.collectFontFamilies=function(a,c,b){for(var d=0;d<this.s.length;d++){var e=this.s[d],f=a,k=b;c.push(e.A);k[e.A]=e.R[f.getStylesheetFormatId()]||[]}};
s.performOptionalActions=function(a,c,b){this.B&&b.whenBodyExists(function(d,e,f,k){return function(){ga(d.B,e,k);var g=d.B;if(g.V){g=g.V.buildUrl(k.isHttps());k.loadScript(g)}var h=d.B;g=d.w;if(h.K){h=h.K.j(g,f,k);h.setAttribute("id","typekit-badge-"+g);k.insertInto("body",h)}}}(this,a,c,b))};function U(a,c,b,d,e){this.pa=a;this.i=c;this.f=b;this.k=d;this.p=e;this.n=[]}U.prototype.C=function(a){this.n.push(a)};
U.prototype.load=function(a,c){var b=a,d=c||{};if(typeof b=="string")b=[b];else if(b&&b.length)b=b;else{d=b||{};b=[]}if(b.length)for(var e=this,f=b.length,k=0;k<b.length;k++)this.ba(b[k],function(){--f==0&&e.J(d)});else this.J(d)};U.prototype.ba=function(a,c){this.i.loadScript(this.pa.buildUrl(this.i.isHttps(),"/"+a+".js"),c)};
U.prototype.J=function(a){if(a.userAgent)this.f=(new w(a.userAgent,document)).parse();a=new ba(this.i,this.k,a);for(var c=new T,b=0;b<this.n.length;b++)this.n[b].addBrowsersToBrowserSet(c);c=c.findBrowser(this.f);for(b=0;b<this.n.length;b++)this.n[b].init(this.i);if(c){a.i.appendClassName(a.k,a.l.j(a.m,"loading"));E(a,"loading");ia(this,c,a)}else D(a);this.n=[]};
function ia(a,c,b){b=new G(a.i,b,{H:function(f){return f.offsetWidth}},a.p,function(){return+new Date});for(var d=0;d<a.n.length;d++){var e=a.n[d];if(e.supportsBrowser(c)){e.load(a.i,b,c,d==a.n.length-1);e.performOptionalActions(window,a.f,a.i)}}}function V(a,c,b){this.t=a;this.i=c;this.p=b;this.n=[]}V.prototype.C=function(a){this.n.push(a)};
V.prototype.load=function(){var a=this.t.__webfonttypekitmodule__;if(a)for(var c=0;c<this.n.length;c++){var b=this.n[c],d=a[b.getId()];if(d){var e=this.i,f=this.p;d(function(k,g,h){var m=new T;b.addBrowsersToBrowserSet(m);g=[];var o={};if(m=m.findBrowser(k)){b.init(e);b.load(e,l,m,f);b.collectFontFamilies(m,g,o);b.performOptionalActions(window,k,e,f)}h(!!m,g,o)})}}};function ja(a,c,b,d){this.t=a;this.o=c;this.da=b;this.ea=d}
ja.prototype.j=function(a,c,b){var d=this.o.createElement("img");d.setAttribute("width",62);d.setAttribute("height",25);d.setAttribute("src",this.da.buildUrl(b.isHttps(),"/default.gif"));d.setAttribute("class","typekit-badge");d.setAttribute("alt","Fonts by Typekit");d.setAttribute("title","Information about the fonts used on this site");d.style.position="fixed";d.style.zIndex=2E9;d.style.right=0;d.style.bottom=0;d.style.cursor="pointer";d.style.border=0;if(c.getName()!="Opera")d.style.content="none";
d.style.display="inline";d.style["float"]="none";d.style.height="25px";d.style.left="auto";d.style.margin=0;d.style.maxHeight="25px";d.style.maxWidth="62px";d.style.minHeight="25px";d.style.minWidth="62px";d.style.orphans=2;d.style.outline="none";d.style.overflow="visible";d.style.padding=0;d.style.pageBreakAfter="auto";d.style.pageBreakBefore="auto";d.style.pageBreakInside="auto";d.style.tableLayout="auto";d.style.textIndent=0;d.style.top="auto";d.style.unicodeBidi="normal";d.style.verticalAlign=
"baseline";d.style.visibility="visible";d.style.widows=2;d.style.width="65px";var e=this.o,f=this.ea.buildUrl(q,"/"+a);W(this,d,"click",function(){e.location.href=f});if(c.getName()=="MSIE"){d.style.position="absolute";var k=this;a=function(){var g=ka(k,"scrollLeft","scrollTop"),h=ka(k,"clientWidth","clientHeight");d.style.bottom="auto";d.style.right="auto";d.style.top=g[1]+h[1]-25+"px";d.style.left=g[0]+h[0]-3-62+"px"};W(this,this.t,"scroll",a);W(this,this.t,"resize",a)}return d};
function ka(a,c,b){var d=0,e=0;a=a.o;if(a.documentElement&&(a.documentElement[c]||a.documentElement[b])){d=a.documentElement[c];e=a.documentElement[b]}else if(a.body&&(a.body[c]||a.body[b])){d=a.body[c];e=a.body[b]}return[d,e]}function W(a,c,b,d){if(c.attachEvent){var e=a.t;c["e"+b+d]=d;c[b+d]=function(){c["e"+b+d](e.event)};c.attachEvent("on"+b,c[b+d])}else c.addEventListener(b,d,q)}var X=new T;
X.addBrowser(new S("chrome6-win2003-win7-winvista-winxp","e",function(a,c,b,d,e,f,k){var g=q;g=(g=(g=(g=g||(e=="Windows"&&f=="5.1"?i:q))||(e=="Windows"&&f=="5.2"?i:q))||(e=="Windows"&&f=="6.0"?i:q))||(e=="Windows"&&f=="6.1"?i:q);if(!g)return q;return function(h,m){if(h=="Chrome"){var o=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(m);if(o)if(parseFloat(o[1])>=6)return i}}(a,c,b,d,e,f,k)}));
X.addBrowser(new S("ie-win2003-win7-winvista-winxp","c",function(a,c,b,d,e,f,k){var g=q;g=(g=(g=(g=g||(e=="Windows"&&f=="5.1"?i:q))||(e=="Windows"&&f=="5.2"?i:q))||(e=="Windows"&&f=="6.0"?i:q))||(e=="Windows"&&f=="6.1"?i:q);if(!g)return q;return function(h,m,o,p,j,n,F){if(h=="MSIE"){if(h=/([0-9]+.[0-9]+)/.exec(m))return parseFloat(h[1])>=6&&(F===undefined||F<9);return q}}(a,c,b,d,e,f,k)}));
X.addBrowser(new S("air-linux-osx-win","b",function(a,c,b,d,e,f,k){var g=q;g=(g=(g=g||(e=="Windows"&&f=="Unknown"?i:q))||function(h,m,o,p,j,n){h=/^([0-9]+)(_|.)([0-9]+)/.exec(n);if(j=="Macintosh"&&h){j=parseInt(h[1],10);n=parseInt(h[3],10);if(j==10)return n>3;else if(j>10)return i}else return j=="Macintosh"&&n=="Unknown"?i:q}(a,c,b,d,e,f,k))||(e=="Ubuntu"||e=="Linux"?i:q);if(!g)return q;return function(h,m){if(h=="AdobeAIR"){var o=/([0-9]+.[0-9]+)/.exec(m);if(o)return parseFloat(o[1])>=2.5}return q}(a,
c,b,d,e,f,k)}));
X.addBrowser(new S("safari-android-ipad-iphone","a",function(a,c,b,d,e,f,k){var g=q;g=(g=(g=g||function(h,m,o,p,j,n){h=/([0-9]+).([0-9]+)/.exec(n);if(j=="Android"&&h){j=parseInt(h[1]);h=parseInt(h[2]);return j>2||j==2&&h>=2}else return q}(a,c,b,d,e,f,k))||function(h,m,o,p,j,n){if(j=="iPad"){if(m=/^([0-9]+)_([0-9]+)/.exec(n)){h=parseInt(m[1],10);m=parseInt(m[2],10);return h==4?m>1:h>4?i:q}}else return q}(a,c,b,d,e,f,k))||function(h,m,o,p,j,n){if(j=="iPhone"||j=="iPod"){if(m=/^([0-9]+)_([0-9]+)/.exec(n)){h=parseInt(m[1],
10);m=parseInt(m[2],10);return h==4?m>1:h>4?i:q}}else return q}(a,c,b,d,e,f,k);if(!g)return q;return function(h,m,o,p,j){if(h=="Safari"&&o=="AppleWebKit"||h=="Unknown"&&o=="AppleWebKit"&&(j=="iPhone"||j=="iPad"))if(h=/([0-9]+.[0-9]+)/.exec(p))return parseFloat(h[1])>=525.13;return q}(a,c,b,d,e,f,k)}));
X.addBrowser(new S("ff36-linux-osx-win2003-win7-winvista-winxp","e",function(a,c,b,d,e,f,k){var g=q;g=(g=(g=(g=(g=(g=g||(e=="Windows"&&f=="5.1"?i:q))||(e=="Windows"&&f=="5.2"?i:q))||(e=="Windows"&&f=="6.0"?i:q))||(e=="Windows"&&f=="6.1"?i:q))||function(h,m,o,p,j,n){h=/^([0-9]+)(_|.)([0-9]+)/.exec(n);if(j=="Macintosh"&&h){j=parseInt(h[1],10);n=parseInt(h[3],10);if(j==10)return n>3;else if(j>10)return i}else return j=="Macintosh"&&n=="Unknown"?i:q}(a,c,b,d,e,f,k))||(e=="Ubuntu"||e=="Linux"?i:q);if(!g)return q;
return function(h,m,o,p){if(o=="Gecko")if(m=/([0-9]+.[0-9]+)(.([0-9]+)|)/.exec(p)){h=parseFloat(m[1]);m=parseInt(m[3],10);return h>1.9||h>=1.9&&m>1}return q}(a,c,b,d,e,f,k)}));
X.addBrowser(new S("opera-linux-osx-win2003-win7-winvista-winxp","b",function(a,c,b,d,e,f,k){var g=q;g=(g=(g=(g=(g=(g=g||(e=="Windows"&&f=="5.1"?i:q))||(e=="Windows"&&f=="5.2"?i:q))||(e=="Windows"&&f=="6.0"?i:q))||(e=="Windows"&&f=="6.1"?i:q))||function(h,m,o,p,j,n){h=/^([0-9]+)(_|.)([0-9]+)/.exec(n);if(j=="Macintosh"&&h){j=parseInt(h[1],10);n=parseInt(h[3],10);if(j==10)return n>3;else if(j>10)return i}else return j=="Macintosh"&&n=="Unknown"?i:q}(a,c,b,d,e,f,k))||(e=="Ubuntu"||e=="Linux"?i:q);if(!g)return q;
a=a=="Opera"?parseFloat(c)>=10.54:q;return a}));
X.addBrowser(new S("safari-osx-win2003-win7-winvista-winxp","b",function(a,c,b,d,e,f,k){var g=q;g=(g=(g=(g=(g=g||(e=="Windows"&&f=="5.1"?i:q))||(e=="Windows"&&f=="5.2"?i:q))||(e=="Windows"&&f=="6.0"?i:q))||(e=="Windows"&&f=="6.1"?i:q))||function(h,m,o,p,j,n){h=/^([0-9]+)(_|.)([0-9]+)/.exec(n);if(j=="Macintosh"&&h){j=parseInt(h[1],10);n=parseInt(h[3],10);if(j==10)return n>3;else if(j>10)return i}else return j=="Macintosh"&&n=="Unknown"?i:q}(a,c,b,d,e,f,k);if(!g)return q;return function(h,m,o,p,j){if(h==
"Safari"&&o=="AppleWebKit"||h=="Unknown"&&o=="AppleWebKit"&&(j=="iPhone"||j=="iPad"))if(h=/([0-9]+.[0-9]+)/.exec(p))return parseFloat(h[1])>=525.13;return q}(a,c,b,d,e,f,k)}));
X.addBrowser(new S("chrome6-linux-osx","d",function(a,c,b,d,e,f,k){var g=q;g=(g=g||function(h,m,o,p,j,n){h=/^([0-9]+)(_|.)([0-9]+)/.exec(n);if(j=="Macintosh"&&h){j=parseInt(h[1],10);n=parseInt(h[3],10);if(j==10)return n>3;else if(j>10)return i}else return j=="Macintosh"&&n=="Unknown"?i:q}(a,c,b,d,e,f,k))||(e=="Ubuntu"||e=="Linux"?i:q);if(!g)return q;return function(h,m){if(h=="Chrome"){var o=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(m);if(o)if(parseFloat(o[1])>=6)return i}}(a,c,b,d,e,f,k)}));
X.addBrowser(new S("ie9-winvista","h",function(a,c,b,d,e,f,k){var g=q;g=g||(e=="Windows"&&f=="6.0"?i:q);if(!g)return q;return function(h,m,o,p,j,n,F){if(h=="MSIE"){if(h=/([0-9]+.[0-9]+)/.exec(m))return parseFloat(h[1])>=9&&F>=9;return q}}(a,c,b,d,e,f,k)}));
X.addBrowser(new S("ff35-linux-osx-win2003-win7-winvista-winxp","b",function(a,c,b,d,e,f,k){var g=q;g=(g=(g=(g=(g=(g=g||(e=="Windows"&&f=="5.1"?i:q))||(e=="Windows"&&f=="5.2"?i:q))||(e=="Windows"&&f=="6.0"?i:q))||(e=="Windows"&&f=="6.1"?i:q))||function(h,m,o,p,j,n){h=/^([0-9]+)(_|.)([0-9]+)/.exec(n);if(j=="Macintosh"&&h){j=parseInt(h[1],10);n=parseInt(h[3],10);if(j==10)return n>3;else if(j>10)return i}else return j=="Macintosh"&&n=="Unknown"?i:q}(a,c,b,d,e,f,k))||(e=="Ubuntu"||e=="Linux"?i:q);if(!g)return q;
return function(h,m,o,p){if(o=="Gecko"){h=/1.9.1b[1-3]{1}/;return/1.9.1/.test(p)&&!h.test(p)}return q}(a,c,b,d,e,f,k)}));X.addBrowser(new S("ie9-win7","g",function(a,c,b,d,e,f,k){var g=q;g=g||(e=="Windows"&&f=="6.1"?i:q);if(!g)return q;return function(h,m,o,p,j,n,F){if(h=="MSIE"){if(h=/([0-9]+.[0-9]+)/.exec(m))return parseFloat(h[1])>=9&&F>=9;return q}}(a,c,b,d,e,f,k)}));
X.addBrowser(new S("chrome-linux-osx-win2003-win7-winvista-winxp","b",function(a,c,b,d,e,f,k){var g=q;g=(g=(g=(g=(g=(g=g||(e=="Windows"&&f=="5.1"?i:q))||(e=="Windows"&&f=="5.2"?i:q))||(e=="Windows"&&f=="6.0"?i:q))||(e=="Windows"&&f=="6.1"?i:q))||function(h,m,o,p,j,n){h=/^([0-9]+)(_|.)([0-9]+)/.exec(n);if(j=="Macintosh"&&h){j=parseInt(h[1],10);n=parseInt(h[3],10);if(j==10)return n>3;else if(j>10)return i}else return j=="Macintosh"&&n=="Unknown"?i:q}(a,c,b,d,e,f,k))||(e=="Ubuntu"||e=="Linux"?i:q);if(!g)return q;
return function(h,m){if(h=="Chrome"){var o=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(m);if(o){var p=parseFloat(o[1]),j=parseInt(o[2],10);o=parseInt(o[3],10);if(p>=6)return q;else if(p>4)return i;else if(p==4&&j>249)return i;else if(p==4&&j==249&&o>=4)return i}}return q}(a,c,b,d,e,f,k)}));
if(!window.Typekit){var la=new R(q,"use.typekit.com","/"),ma=(new w(navigator.userAgent,document)).parse(),na=new P(document,ma),oa=function(a,c){setTimeout(a,c)},Y=new U(la,na,ma,document.documentElement,oa),Z=new V(window,na,oa);window.Typekit=Y;window.Typekit.load=Y.load;window.Typekit.addKit=Y.C}var pa,qa=l,ra=l,sa=l,ta=l,ua,$;pa=new R(q,"use.typekit.com","/k");qa=new R(q,function(a){return(a=="https:"?"ssl":"www")+".google-analytics.com"},"");ra=new R(q,"use.typekit.com","/badges");
sa=new R(q,"typekit.com","/colophons");ta=new ja(window,document,ra,sa);ua=new function(a,c,b){this.K=a;this.S=c;this.V=b}(ta,qa,l);$=new ha("wxl5kyc");$.setSecurityToken("3bb2a6e53c9684ffdc9a9bf51a5b2a623eba118d7fdad9fb5a88daa2677d17c5e35a0437b9a4ce163eece4381151c6f3323dffcfc5a6cb6c608e27af0e166c40b37108e304b786a00a3f722830fa7de1b0f507f754b655dfd9e95fde777c414729d67edb4b6a8da2b41c89ba55e73b818709f385c8bead4ac7ff3efce56fbbc1ee0b");$.setNestedUrl(pa);$.setKitOptions(ua);
$.addFontFamily(new Q('"museo-slab-1","museo-slab-2"',{a:["n5","n7"],b:["n5","n7"],c:["n5","n7"],d:["n5","n7"],e:["n5","n7"],g:["n5","n7"],h:["n5","n7"]}));$.addCssRule(new function(a,c){this.Aa=a;this.O=c}([".tk-museo-slab"],[{value:'"museo-slab-1","museo-slab-2",serif',name:"font-family"}]));$.addBrowser(X.getBrowserById("air-linux-osx-win"));$.addBrowser(X.getBrowserById("chrome-linux-osx-win2003-win7-winvista-winxp"));$.addBrowser(X.getBrowserById("chrome6-linux-osx"));$.addBrowser(X.getBrowserById("chrome6-win2003-win7-winvista-winxp"));
$.addBrowser(X.getBrowserById("ff35-linux-osx-win2003-win7-winvista-winxp"));$.addBrowser(X.getBrowserById("ff36-linux-osx-win2003-win7-winvista-winxp"));$.addBrowser(X.getBrowserById("ie-win2003-win7-winvista-winxp"));$.addBrowser(X.getBrowserById("ie9-win7"));$.addBrowser(X.getBrowserById("ie9-winvista"));$.addBrowser(X.getBrowserById("opera-linux-osx-win2003-win7-winvista-winxp"));$.addBrowser(X.getBrowserById("safari-android-ipad-iphone"));$.addBrowser(X.getBrowserById("safari-osx-win2003-win7-winvista-winxp"));
if(Z&&Z.t.__webfonttypekitmodule__){Z.C($);Z.load()}else window.Typekit.addKit($);
})(this,document);